shfmt

diff --git a/bin/git-unwip b/bin/git-unwip
--- a/bin/git-unwip
+++ b/bin/git-unwip
@@ -2,8 +2,8 @@
 
 subj=$(git log -1 --pretty=%s)
 if [ "$subj" != "WIP" ]; then
-   echo "Can't unwip non-WIP commit ($subj)" 1>&2
-   exit 1
+	echo "Can't unwip non-WIP commit ($subj)" 1>&2
+	exit 1
 fi
 
 git reset HEAD^
diff --git a/bin/go-splore b/bin/go-splore
--- a/bin/go-splore
+++ b/bin/go-splore
@@ -1,8 +1,8 @@
 #!/bin/sh
 
 if [ -z "$1" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
-base=$(basename $0)
-   cat <<USAGE
+	base=$(basename $0)
+	cat <<USAGE
 usage:
    $base <pkg> [count]
 
@@ -12,7 +12,7 @@ Like so:
 
 Downloads and vendors up to [count] users of <pkg>.  count defaults to 15.
 USAGE
-   exit
+	exit
 fi
 
 pkg=$1
@@ -36,11 +36,11 @@ import (
 HEAD
 
 curl -s "https://godoc.org/$pkg?importers" |
-   grep -F '<tr><td><a href="' |
-   perl -pe 's{.*href="/([^"]+)".*}{$1}' |
-   grep -v internal |
-   head -$count |
-   perl -pe 's/(.*)/\t_ "$1"/'
+	grep -F '<tr><td><a href="' |
+	perl -pe 's{.*href="/([^"]+)".*}{$1}' |
+	grep -v internal |
+	head -$count |
+	perl -pe 's/(.*)/\t_ "$1"/'
 
 cat <<TAIL
 )
@@ -51,25 +51,25 @@ TAIL
 exec >/dev/tty
 
 while true; do
-   out=$(go mod vendor 2>&1)
-   finished=$?
+	out=$(go mod vendor 2>&1)
+	finished=$?
 
-   echo "$out"
+	echo "$out"
 
-   if [ $finished -ne 0 ]; then
-      # go: github.com/dominikh/go-tools@v0.0.0-20190602125119-5a4a2f4a438d: parsing go.mod: unexpected module path "honnef.co/go/tools"
-      #     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-      busted=$(echo "$out" | perl -pe "m/^go: ([^@]+)@[^:]+: .*/; \$_ = qq(\$1\n)")
-      if [ -z "$busted" ]; then
-         echo "Couldn't figure out what was wrong, giving up"
-         exit 2
-      fi
-      for pkg in $busted; do
-         echo "removing $pkg"
-         perl -pe'm(\Q'"$pkg"'\E) && undef $_' <main.go | sponge main.go
-      done
-      continue
-   else
-      break
-   fi
+	if [ $finished -ne 0 ]; then
+		# go: github.com/dominikh/go-tools@v0.0.0-20190602125119-5a4a2f4a438d: parsing go.mod: unexpected module path "honnef.co/go/tools"
+		#     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
+		busted=$(echo "$out" | perl -pe "m/^go: ([^@]+)@[^:]+: .*/; \$_ = qq(\$1\n)")
+		if [ -z "$busted" ]; then
+			echo "Couldn't figure out what was wrong, giving up"
+			exit 2
+		fi
+		for pkg in $busted; do
+			echo "removing $pkg"
+			perl -pe'm(\Q'"$pkg"'\E) && undef $_' <main.go | sponge main.go
+		done
+		continue
+	else
+		break
+	fi
 done
