use new leatherman features to simplify program

diff --git a/bin/gotest b/bin/gotest
--- a/bin/gotest
+++ b/bin/gotest
@@ -1,30 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
-test() {
-   echo ========== $(date) ==========
-
-   # unpack GOTESTARGS back into $@
-   eval "$GOTESTARGS"
-   set -- "${s[@]}"
-
-   go test "$@"
-   echo ==================================================
-}
-
-if [ "$1" = "test" ]; then
-   shift
-   test
-else
-   # Serialize into string
-   GOTESTARGS=$(
-      s=("$@")        # temporary array
-      set | grep ^s=  # `set` serializes a named array
-   )
-   export GOTESTARGS
-
-   # reexec the current script; this works from minotaur and
-   # ensures the reexec code is working on the first run
-   "$0" test
-   leatherman minotaur . -- "$0" test
-fi
-
+# if tests fail print BEL
+exec leatherman minotaur -report . -- sh -c 'go test "$@" || echo "\a"' _ "$@"
